version: '3.9'

volumes:
  db-data: {}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ['CMD-SHELL', 'curl --silent --fail localhost:9200/_cluster/health || exit 1']
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '9200:9200' # backend/src/resources/application.properites references 'elasticsearch:9200'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - '9187:9187'
    expose:
      - 9187
    depends_on:
      elasticsearch:
        condition: service_healthy
      #db:
       # condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reactjs
    ports:
      - '5173:5173'
    depends_on:
      - backend

  db:
    image: mysql:8.0.19
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    ports:
      - '3306:3306'
    environment:
      # - MYSQL_DATABASE=example
      # - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_ROOT_PASSWORD=pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

